services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Secret5555
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
  wordpress:
    build: .
    ports:
      - "8000:8000"
    user: "www-data:www-data"
    volumes:
      - my-contentvolume:/var/local/wordpress/wp-content
  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
volumes:
  my-datavolume:
  my-contentvolume: